package ToFileHandOver;


/**
* ToFileHandOver/HandOverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ToFileHandOver.idl
* 12 марта 2022 г. 1:44:55 MSK
*/

public interface HandOverOperations 
{
  String handOver ();
  void handOver (String newHandOver);
} // interface HandOverOperations
