package ToFileHandOver;


/**
* ToFileHandOver/HandOverHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ToFileHandOver.idl
* 12 марта 2022 г. 1:44:55 MSK
*/

abstract public class HandOverHelper
{
  private static String  _id = "IDL:ToFileHandOver/HandOver:1.0";

  public static void insert (org.omg.CORBA.Any a, ToFileHandOver.HandOver that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ToFileHandOver.HandOver extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ToFileHandOver.HandOverHelper.id (), "HandOver");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ToFileHandOver.HandOver read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HandOverStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ToFileHandOver.HandOver value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ToFileHandOver.HandOver narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ToFileHandOver.HandOver)
      return (ToFileHandOver.HandOver)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ToFileHandOver._HandOverStub stub = new ToFileHandOver._HandOverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ToFileHandOver.HandOver unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ToFileHandOver.HandOver)
      return (ToFileHandOver.HandOver)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ToFileHandOver._HandOverStub stub = new ToFileHandOver._HandOverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
