package ToFileHandOver;


/**
* ToFileHandOver/HandOverPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ToFileHandOver.idl
* 12 марта 2022 г. 1:44:55 MSK
*/

public abstract class HandOverPOA extends org.omg.PortableServer.Servant
 implements ToFileHandOver.HandOverOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_handOver", new java.lang.Integer (0));
    _methods.put ("_set_handOver", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ToFileHandOver/HandOver/_get_handOver
       {
         String $result = null;
         $result = this.handOver ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ToFileHandOver/HandOver/_set_handOver
       {
         String newHandOver = in.read_string ();
         this.handOver (newHandOver);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ToFileHandOver/HandOver:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HandOver _this() 
  {
    return HandOverHelper.narrow(
    super._this_object());
  }

  public HandOver _this(org.omg.CORBA.ORB orb) 
  {
    return HandOverHelper.narrow(
    super._this_object(orb));
  }


} // class HandOverPOA
